---
# tasks file for remarkable_templates_and_splashscreen
- name: Splash Screen - backup
  ansible.builtin.raw: mv /usr/share/remarkable/suspended.png /usr/share/remarkable/suspended.png.old.$(date "+%Y%m%d-%H%M")  # noqa: no-changed-when

- name: Splash Screen - copy to device
  ansible.posix.synchronize:
    src: "splashscreens_to_copy/suspended.png"
    dest: "/usr/share/remarkable/suspended.png"

- name: Templates.json - backup
  ansible.builtin.raw: mv /usr/share/remarkable/templates/templates.json /usr/share/remarkable/templates/templates.json.old.$(date "+%Y%m%d-%H%M")  # noqa: no-changed-when

- name: Copy templates and templates.json to device
  ansible.posix.synchronize:
    src: "templates_to_copy/"
    dest: "/usr/share/remarkable/templates/"

- name: Restart xochitl
  ansible.builtin.raw: systemctl restart xochitl # noqa: no-changed-when
