---
name: CI
on:
  push:
    branches: ["main", "releases/**"]
    #tags: ["v*", "v**", "v.*", "v.**" ]
  pull_request:
    branches: ["main", "releases/**"]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    # prevent stuck jobs
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/set-up-python

      - name: Lint
        uses: ./.github/actions/lint

  molecule:
    needs: [lint]
    name: Test with Ansible Molecule
    runs-on: ubuntu-latest
    # prevent stuck jobs
    timeout-minutes: 20
    strategy:
      matrix:
        distro: [ubuntu2204]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/set-up-python

      - name: Set up Ansible
        uses: ./.github/actions/set-up-ansible

      - name: Set up Molecule
        uses: ./.github/actions/set-up-molecule

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
