---
# see: https://github.com/geerlingguy/ansible-role-docker/blob/8bb277bd7fb7019eb129b4a07194f0364c060203/.github/workflows/release.yml
name: Publish role on Ansible Galaxy
on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    name:  Publish role on Ansible Galaxy
    runs-on: ubuntu-latest
    # prevent stuck jobs
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/set-up-python

      - name: Set up Ansible
        uses: ./.github/actions/set-up-ansible

      - name: Import to Ansible Galaxy
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
